// 하위 분류의 ID와 상위 분류에 대한 설명을 Mapping한 데이터입니다.
export const SUB_TO_TOP: { [id: string]: string } = {
  "astro-ph": "Astrophysics",
  "astro-ph.CO": "Astrophysics",
  "astro-ph.EP": "Astrophysics",
  "astro-ph.GA": "Astrophysics",
  "astro-ph.HE": "Astrophysics",
  "astro-ph.IM": "Astrophysics",
  "astro-ph.SR": "Astrophysics",
  "cond-mat.dis-nn": "Condensed Matter",
  "cond-mat.mes-hall": "Condensed Matter",
  "cond-mat.mtrl-sci": "Condensed Matter",
  "cond-mat.other": "Condensed Matter",
  "cond-mat.quant-gas": "Condensed Matter",
  "cond-mat.soft": "Condensed Matter",
  "cond-mat.stat-mech": "Condensed Matter",
  "cond-mat.str-el": "Condensed Matter",
  "cond-mat.supr-con": "Condensed Matter",
  "gr-qc": "General Relativity and Quantum Cosmology",
  "hep-ex": "High Energy Physics",
  "hep-lat": "High Energy Physics",
  "hep-ph": "High Energy Physics",
  "hep-th": "High Energy Physics",
  "math-ph": "Mathematical Physics",
  "nucl-ex": "Nuclear Experiment",
  "nucl-th": "Nuclear Theory",
  "physics.acc-ph": "Physics",
  "physics.app-ph": "Physics",
  "physics.ao-ph": "Physics",
  "physics.atom-ph": "Physics",
  "physics.atm-clus": "Physics",
  "physics.bio-ph": "Physics",
  "physics.chem-ph": "Physics",
  "physics.class-ph": "Physics",
  "physics.comp-ph": "Physics",
  "physics.data-an": "Physics",
  "physics.flu-dyn": "Physics",
  "physics.gen-ph": "Physics",
  "physics.geo-ph": "Physics",
  "physics.hist-ph": "Physics",
  "physics.ins-det": "Physics",
  "physics.med-ph": "Physics",
  "physics.optics": "Physics",
  "physics.ed-ph": "Physics",
  "physics.soc-ph": "Physics",
  "physics.plasm-ph": "Physics",
  "physics.pop-ph": "Physics",
  "physics.space-ph": "Physics",
  "quant-ph": "Quantum Physics",
  "math.AG": "Mathematics",
  "math.AT": "Mathematics",
  "math.AP": "Mathematics",
  "math.CT": "Mathematics",
  "math.CA": "Mathematics",
  "math.CO": "Mathematics",
  "math.AC": "Mathematics",
  "math.CV": "Mathematics",
  "math.DG": "Mathematics",
  "math.DS": "Mathematics",
  "math.FA": "Mathematics",
  "math.GM": "Mathematics",
  "math.GT": "Mathematics",
  "math.GR": "Mathematics",
  "math.HO": "Mathematics",
  "math.IT": "Mathematics",
  "math.KT": "Mathematics",
  "math.LO": "Mathematics",
  "math.MG": "Mathematics",
  "math.NT": "Mathematics",
  "math.NA": "Mathematics",
  "math.OA": "Mathematics",
  "math.OC": "Mathematics",
  "math.PR": "Mathematics",
  "math.QA": "Mathematics",
  "math.RT": "Mathematics",
  "math.RA": "Mathematics",
  "math.SP": "Mathematics",
  "math.ST": "Mathematics",
  "math.SG": "Mathematics",
  "cs.AI": "Computer Science",
  "cs.CL": "Computer Science",
  "cs.CC": "Computer Science",
  "cs.CE": "Computer Science",
  "cs.CG": "Computer Science",
  "cs.CV": "Computer Science",
  "cs.CY": "Computer Science",
  "cs.CR": "Computer Science",
  "cs.DS": "Computer Science",
  "cs.DB": "Computer Science",
  "cs.DL": "Computer Science",
  "cs.DM": "Computer Science",
  "cs.DC": "Computer Science",
  "cs.ET": "Computer Science",
  "cs.FL": "Computer Science",
  "cs.GL": "Computer Science",
  "cs.GR": "Computer Science",
  "cs.AR": "Computer Science",
  "cs.HC": "Computer Science",
  "cs.IR": "Computer Science",
  "cs.IT": "Computer Science",
  "cs.LG": "Computer Science",
  "cs.LO": "Computer Science",
  "cs.MS": "Computer Science",
  "cs.MA": "Computer Science",
  "cs.MM": "Computer Science",
  "cs.NI": "Computer Science",
  "cs.NE": "Computer Science",
  "cs.OS": "Computer Science",
  "cs.OH": "Computer Science",
  "cs.PF": "Computer Science",
  "cs.PL": "Computer Science",
  "cs.RO": "Computer Science",
  "cs.SI": "Computer Science",
  "cs.SE": "Computer Science",
  "cs.SD": "Computer Science",
  "cs.SC": "Computer Science",
  "cs.SY": "Computer Science",
  "q-bio.BM": "Quantitative Biology",
  "q-bio.CB": "Quantitative Biology",
  "q-bio.GN": "Quantitative Biology",
  "q-bio.MN": "Quantitative Biology",
  "q-bio.NC": "Quantitative Biology",
  "q-bio.PE": "Quantitative Biology",
  "q-bio.QM": "Quantitative Biology",
  "q-bio.SC": "Quantitative Biology",
  "q-bio.TO": "Quantitative Biology",
  "q-fin.CP": "Quantitative Finance",
  "q-fin.EC": "Quantitative Finance",
  "q-fin.GN": "Quantitative Finance",
  "q-fin.MF": "Quantitative Finance",
  "q-fin.PM": "Quantitative Finance",
  "q-fin.PR": "Quantitative Finance",
  "q-fin.RM": "Quantitative Finance",
  "q-fin.ST": "Quantitative Finance",
  "q-fin.TR": "Quantitative Finance",
  "stat.AP": "Statistics",
  "stat.CO": "Statistics",
  "stat.ML": "Statistics",
  "stat.ME": "Statistics",
  "stat.OT": "Statistics",
  "stat.TH": "Statistics",
  "eess.AS": "Electrical Engineering and Systems Science",
  "eess.IV": "Electrical Engineering and Systems Science",
  "eess.SP": "Electrical Engineering and Systems Science",
  "eess.SY": "Electrical Engineering and Systems Science",
  "econ.EM": "Economics",
  "econ.GN": "Economics",
  "econ.TH": "Economics",
};

// 모든 하위 분류의 ID와 상세 설명을 Mapping한 데이터입니다.
// 초기 단계에서는 FE 단에 미리 정의 후 사용하지만, 이후 단계에서는 외부로부터 정보를 가져오는 방식으로 수정할 예정입니다.
export const SUB_ID_DESC: { [id: string]: string } = {
  "astro-ph": "Astrophysics",
  "astro-ph.CO": "Cosmology and Nongalactic Astrophysics",
  "astro-ph.EP": "Earth and Planetary Astrophysics",
  "astro-ph.GA": "Astrophysics of Galaxies",
  "astro-ph.HE": "High Energy Astrophysical Phenomena",
  "astro-ph.IM": "Instrumentation and Methods for Astrophysics",
  "astro-ph.SR": "Solar and Stellar Astrophysics",
  "cond-mat.dis-nn": "Disordered Systems and Neural Networks",
  "cond-mat.mes-hall": "Mesoscale and Nanoscale Physics",
  "cond-mat.mtrl-sci": "Materials Science",
  "cond-mat.other": "Other Condensed Matter",
  "cond-mat.quant-gas": "Quantum Gases",
  "cond-mat.soft": "Soft Condensed Matter",
  "cond-mat.stat-mech": "Statistical Mechanics",
  "cond-mat.str-el": "Strongly Correlated Electrons",
  "cond-mat.supr-con": "Superconductivity",
  "gr-qc": "General Relativity and Quantum Cosmology",
  "hep-ex": "High Energy Physics - Experiment",
  "hep-lat": "High Energy Physics - Lattice",
  "hep-ph": "High Energy Physics - Phenomenology",
  "hep-th": "High Energy Physics - Theory",
  "math-ph": "Mathematical Physics",
  "nucl-ex": "Nuclear Experiment",
  "nucl-th": "Nuclear Theory",
  "physics.acc-ph": "Accelerator Physics",
  "physics.app-ph": "Applied Physics",
  "physics.ao-ph": "Atmospheric and Oceanic Physics",
  "physics.atom-ph": "Atomic Physics",
  "physics.atm-clus": "Atomic and Molecular Clusters",
  "physics.bio-ph": "Biological Physics",
  "physics.chem-ph": "Chemical Physics",
  "physics.class-ph": "Classical Physics",
  "physics.comp-ph": "Computational Physics",
  "physics.data-an": "Data Analysis, Statistics and Probability",
  "physics.flu-dyn": "Fluid Dynamics",
  "physics.gen-ph": "General Physics",
  "physics.geo-ph": "Geophysics",
  "physics.hist-ph": "History and Philosophy of Physics",
  "physics.ins-det": "Instrumentation and Detectors",
  "physics.med-ph": "Medical Physics",
  "physics.optics": "Optics",
  "physics.ed-ph": "Physics Education",
  "physics.soc-ph": "Physics and Society",
  "physics.plasm-ph": "Plasma Physics",
  "physics.pop-ph": "Popular Physics",
  "physics.space-ph": "Space Physics",
  "quant-ph": "Quantum Physics",
  "math.AG": "Algebraic Geometry",
  "math.AT": "Algebraic Topology",
  "math.AP": "Analysis of PDEs",
  "math.CT": "Category Theory",
  "math.CA": "Classical Analysis and ODEs",
  "math.CO": "Combinatorics",
  "math.AC": "Commutative Algebra",
  "math.CV": "Complex Variables",
  "math.DG": "Differential Geometry",
  "math.DS": "Dynamical Systems",
  "math.FA": "Functional Analysis",
  "math.GM": "General Mathematics",
  "math.GT": "Geometric Topology",
  "math.GR": "Group Theory",
  "math.HO": "History and Overview",
  "math.IT": "Information Theory",
  "math.KT": "K-Theory and Homology",
  "math.LO": "Logic",
  "math.MG": "Metric Geometry",
  "math.NT": "Number Theory",
  "math.NA": "Numerical Analysis",
  "math.OA": "Operator Algebras",
  "math.OC": "Optimization and Control",
  "math.PR": "Probability",
  "math.QA": "Quantum Algebra",
  "math.RT": "Representation Theory",
  "math.RA": "Rings and Algebras",
  "math.SP": "Spectral Theory",
  "math.ST": "Statistics Theory",
  "math.SG": "Symplectic Geometry",
  "cs.AI": "Artificial Intelligence",
  "cs.CL": "Computation and Language",
  "cs.CC": "Computational Complexity",
  "cs.CE": "Computational Engineering, Finance, and Science",
  "cs.CG": "Computational Geometry",
  "cs.CV": "Computer Vision and Pattern Recognition",
  "cs.CY": "Computers and Society",
  "cs.CR": "Cryptography and Security",
  "cs.DS": "Data Structures and Algorithms",
  "cs.DB": "Databases",
  "cs.DL": "Digital Libraries",
  "cs.DM": "Discrete Mathematics",
  "cs.DC": "Distributed, Parallel, and Cluster Computing",
  "cs.ET": "Emerging Technologies",
  "cs.FL": "Formal Languages and Automata Theory",
  "cs.GL": "General Literature",
  "cs.GR": "Graphics",
  "cs.AR": "Hardware Architecture",
  "cs.HC": "Human-Computer Interaction",
  "cs.IR": "Information Retrieval",
  "cs.IT": "Information Theory",
  "cs.LG": "Machine Learning",
  "cs.LO": "Logic in Computer Science",
  "cs.MS": "Mathematical Software",
  "cs.MA": "Multiagent Systems",
  "cs.MM": "Multimedia",
  "cs.NI": "Networking and Internet Architecture",
  "cs.NE": "Neural and Evolutionary Computing",
  "cs.NA": "Numerical Analysis",
  "cs.OS": "Operating Systems",
  "cs.OH": "Other Computer Science",
  "cs.PF": "Performance",
  "cs.PL": "Programming Languages",
  "cs.RO": "Robotics",
  "cs.SI": "Social and Information Networks",
  "cs.SE": "Software Engineering",
  "cs.SD": "Sound",
  "cs.SC": "Symbolic Computation",
  "cs.SY": "Systems and Control",
  "q-bio.BM": "Biomolecules",
  "q-bio.CB": "Cell Behavior",
  "q-bio.GN": "Genomics",
  "q-bio.MN": "Molecular Networks",
  "q-bio.NC": "Neurons and Cognition",
  "q-bio.PE": "Populations and Evolution",
  "q-bio.QM": "Quantitative Methods",
  "q-bio.SC": "Subcellular Processes",
  "q-bio.TO": "Tissues and Organs",
  "q-fin.CP": "Computational Finance",
  "q-fin.EC": "Economics",
  "q-fin.GN": "General Finance",
  "q-fin.MF": "Mathematical Finance",
  "q-fin.PM": "Portfolio Management",
  "q-fin.PR": "Pricing of Securities",
  "q-fin.RM": "Risk Management",
  "q-fin.ST": "Statistical Finance",
  "q-fin.TR": "Trading and Market Microstructure",
  "stat.AP": "Applications",
  "stat.CO": "Computation",
  "stat.ML": "Machine Learning",
  "stat.ME": "Methodology",
  "stat.OT": "Other Statistics",
  "stat.TH": "Statistics Theory",
  "eess.AS": "Audio and Speech Processing",
  "eess.IV": "Image and Video Processing",
  "eess.SP": "Signal Processing",
  "eess.SY": "Systems and Control",
  "econ.EM": "Econometrics",
  "econ.GN": "General Economics",
  "econ.TH": "Theoretical Economics",
};
