export type Journal = string[];

export const Journal: Journal = [
  "Nature",
  "Science",
  "Physical Review Letters",
  "The Astrophysical Journal",
  "Journal of High Energy Physics",
  "Monthly Notices of the Royal Astronomical Society",
  "Proceedings of the National Academy of Sciences",
  "IEEE Transactions on Neural Networks and Learning Systems",
  "Journal of Machine Learning Research",
  "Neural Information Processing Systems (NeurIPS)",
  "IEEE Transactions on Pattern Analysis and Machine Intelligence",
  "Communications of the ACM",
  "Journal of Statistical Physics",
  "Annals of Mathematics",
  "Cell",
  "Nature Physics",
  "Nature Astronomy",
  "Journal of the American Mathematical Society",
  "Proceedings of the IEEE",
  "IEEE Transactions on Information Theory",
  "Nature Neuroscience",
  "Nature Biotechnology",
  "Nature Medicine",
  "Bioinformatics",
  "New England Journal of Medicine",
  "IEEE Transactions on Image Processing",
  "European Physical Journal C",
  "Journal of Cosmology and Astroparticle Physics",
  "Journal of Mathematical Physics",
  "Science Advances",
  "Astrophysical Journal Letters",
  "Physical Review D",
  "Journal of Fluid Mechanics",
  "PLoS Biology",
  "Journal of Chemical Physics",
  "Artificial Intelligence",
  "Journal of Computational Physics",
  "Annual Review of Astronomy and Astrophysics",
  "The Lancet",
  "Nature Chemistry",
  "IEEE Transactions on Medical Imaging",
  "Advances in Neural Information Processing Systems (NeurIPS)",
  "International Journal of Computer Vision",
  "Quantum Information Processing",
  "SIAM Journal on Applied Mathematics",
  "Nature Reviews Genetics",
  "Proceedings of the Royal Society A",
  "Biophysical Journal",
  "Journal of Computational and Graphical Statistics",
  "Nature Methods",
];
